# Generated by Django 3.0.6 on 2020-05-19 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0082_auto_20200516_0052'),
        ('polls', '0002_auto_20200519_2038'),
    ]

    operations = [
    ]
