# Generated by Django 3.0.6 on 2020-05-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0084_auto_20200520_0342'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_role'),
        ),
    ]
