# Generated by Django 3.0.6 on 2020-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0085_auto_20200520_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
