# Generated by Django 3.0.6 on 2020-06-13 03:57

from django.db import migrations, models
import polls.models.course
from polls.models.course import random_code

def randomize_all(apps, schema_editor):
    Course = apps.get_model("polls", "Course")
    db_alias = schema_editor.connection.alias
    for course in Course.objects.using(db_alias).all():
        course.secret_code = random_code()
        course.save()

def undo_rando(apps, schema_editor):
    Course = apps.get_model("polls", "Course")
    db_alias = schema_editor.connection.alias
    secret = random_code()
    for course in Course.objects.using(db_alias).all():
        course.secret_code = secret
        course.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0089_auto_20200613_0355'),
    ]

    operations = [
        migrations.RunPython(randomize_all, undo_rando),
        migrations.AlterField(
            model_name='course',
            name='secret_code',
            field=models.CharField(default=polls.models.course.random_code, max_length=10, unique=True),
        ),
    ]
