# Generated by Django 3.0.6 on 2020-06-23 22:28

from django.db import migrations, models
from polls.models.user import UserProfile

def migrate_authors(apps, schema_editor):
    Question = apps.get_model("polls", "Question")
    db_alias = schema_editor.connection.alias
    for question in Question.objects.using(db_alias).all():
        user = question.owner
        user2 = UserProfile.objects.using(db_alias).get(pk=user.id)
        question.author = user2.get_full_name() + ' email: '+user2.email
        question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0093_quiz_is_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
        migrations.RunPython(migrate_authors)
    ]
