# Generated by Django 3.0.8 on 2020-09-23 19:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0095_auto_20200902_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='identifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
