# Generated by Django 3.0.8 on 2020-09-30 17:15

from django.db import migrations
import polls.models.variable


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0096_auto_20200923_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='variables',
            field=polls.models.variable.VariableField(),
        ),
    ]
