# Generated by Django 3.0.8 on 2020-11-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0098_auto_20201021_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='patterntype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
