# Generated by Django 3.0.8 on 2020-11-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0099_response_patterntype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_hidden',
        ),
    ]
