# Generated by Django 3.0.8 on 2020-12-02 18:27

from django.db import migrations
import polls.models.gradepolicy


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0100_remove_quiz_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade_policy',
            field=polls.models.gradepolicy.GradePolicyField(default=polls.models.gradepolicy.GradePolicy(3, 0, 0.0, 'max')),
        ),
    ]
