# Generated by Django 2.1.4 on 2019-01-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_responseattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionattempt',
            old_name='quiz_attemp',
            new_name='quiz_attempt',
        ),
        migrations.RenameField(
            model_name='responseattempt',
            old_name='question_attemp',
            new_name='question_attempt',
        ),
    ]
