# Generated by Django 2.1.5 on 2019-03-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190220_2228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'position'), ('quiz', 'question')},
        ),
    ]
