# Generated by Django 2.1.5 on 2019-03-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190325_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='type',
            new_name='rtype',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question', 'name')},
        ),
    ]
