# Generated by Django 2.1.5 on 2019-04-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190325_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='author',
        ),
    ]
