# Generated by Django 2.1.5 on 2019-04-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_questionattempt_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseattempt',
            name='author',
        ),
    ]
