# Generated by Django 2.1.5 on 2019-04-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190409_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
