# Generated by Django 2.1.5 on 2019-04-29 22:53

from django.db import migrations
import polls.models.gradepolicy


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_response_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='grade_policy',
            field=polls.models.gradepolicy.GradePolicyField(default=polls.models.gradepolicy.GradePolicy(3)),
        ),
    ]
