# Generated by Django 2.2.1 on 2019-05-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_response_grade_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='polls.Tag'),
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='polls.Tag'),
        ),
    ]
