# Generated by Django 2.2.1 on 2019-05-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20190518_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='test', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
