# Generated by Django 2.2.1 on 2019-05-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190518_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='background',
            new_name='text',
        ),
    ]
