# Generated by Django 2.2.1 on 2019-05-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20190528_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='text',
        ),
    ]
