# Generated by Django 2.2.1 on 2019-05-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20190528_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correction',
        ),
        migrations.AlterField(
            model_name='answer',
            name='accuracy',
            field=models.FloatField(),
        ),
    ]
