# Generated by Django 2.2.1 on 2019-05-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20190528_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='accuracy',
            new_name='grade',
        ),
    ]
