# Generated by Django 2.2.1 on 2019-05-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20190528_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question', 'index')},
        ),
        migrations.RemoveField(
            model_name='response',
            name='name',
        ),
    ]
