# Generated by Django 2.2.1 on 2019-06-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20190530_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='weight',
        ),
    ]
