# Generated by Django 2.2.1 on 2019-06-04 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_remove_question_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='weight',
            new_name='mark',
        ),
    ]
