# Generated by Django 2.2.1 on 2019-06-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20190604_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
