# Generated by Django 2.2.1 on 2019-06-04 01:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import polls.models.response


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_delete_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='rtype',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=polls.models.response.default_string_dict),
        ),
    ]
