# Generated by Django 2.2.1 on 2019-06-04 03:15

import django.contrib.postgres.fields
from django.db import migrations
import polls.models.variable


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_auto_20190604_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=polls.models.variable.VariableField(), default=list, size=None),
        ),
    ]
