# Generated by Django 2.2.1 on 2019-06-16 21:09

import django.contrib.postgres.fields
from django.db import migrations
import polls.models.variable


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20190616_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='variables',
            field=django.contrib.postgres.fields.ArrayField(base_field=polls.models.variable.VariableField(), blank=True, default=list, size=None),
        ),
    ]
