# Generated by Django 2.2.1 on 2019-07-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_auto_20190616_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
