# Generated by Django 2.2.1 on 2019-07-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_auto_20190705_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='create_date',
        ),
    ]
