# Generated by Django 2.2.1 on 2019-07-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_remove_question_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='create_date',
        ),
    ]
