# Generated by Django 2.2.1 on 2019-07-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_remove_quiz_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
    ]
