# Generated by Django 2.2.1 on 2019-07-05 22:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_remove_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
