# Generated by Django 2.2.1 on 2019-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_quiz_show_solution_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='weight',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
