# Generated by Django 2.2.1 on 2019-07-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_quiz_later_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='later_time',
            new_name='late_time',
        ),
    ]
