# Generated by Django 2.2.1 on 2019-07-16 19:22

from django.db import migrations, models
import polls.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_auto_20190710_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(max_length=254, null=True, upload_to='../../storage', validators=[polls.models.user.validate_avatar_size], verbose_name='avatar'),
        ),
    ]
