# Generated by Django 2.2.1 on 2019-07-17 19:20

from django.db import migrations, models
import polls.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(max_length=254, null=True, upload_to='storage', validators=[polls.models.user.validate_avatar_size], verbose_name='avatar'),
        ),
    ]
