# Generated by Django 2.2.1 on 2019-08-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20190717_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
