# Generated by Django 2.2.1 on 2019-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_emailcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_active',
            field=models.BooleanField(default=False),
        ),
    ]
