# Generated by Django 2.2.1 on 2019-08-07 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_userprofile_email_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
