# Generated by Django 2.2.1 on 2019-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_auto_20190807_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='available',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
