# Generated by Django 2.2.1 on 2019-08-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_emailcode_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='responseattempt',
            name='question_attempt',
        ),
        migrations.RemoveField(
            model_name='responseattempt',
            name='response',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='ResponseAttempt',
        ),
    ]
