# Generated by Django 2.2.1 on 2019-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fullname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='shortname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
