# Generated by Django 2.2.1 on 2019-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0060_permission2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
