# Generated by Django 2.2.5 on 2019-10-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0065_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='bonus',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
