# Generated by Django 2.2.5 on 2019-10-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0067_auto_20191008_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('python', 'python')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
