# Generated by Django 2.2.5 on 2019-11-25 00:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import polls.models.question


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0070_attempt_quiz_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=polls.models.question.default_para_dict),
        ),
    ]
