# Generated by Django 2.2.5 on 2019-11-25 00:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import polls.models.question


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0071_auto_20191125_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=polls.models.question.default_para_dict),
        ),
    ]
