# Generated by Django 2.2.5 on 2019-11-25 00:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0072_auto_20191125_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
