# Generated by Django 2.2.2 on 2020-02-25 21:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import polls.models.question


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0075_auto_20200225_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=polls.models.question.default_para_dict),
        ),
    ]
