# Generated by Django 2.2.2 on 2020-03-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0076_auto_20200225_2100'),
        ('polls', '0080_auto_20200302_2121'),
    ]

    operations = [
    ]
