# Generated by Django 3.0.6 on 2020-05-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0081_merge_20200303_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_instructor',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
