# Generated by Django 3.0.6 on 2020-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0084_auto_20200519_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'nonediting ta'), (3, 'editing ta'), (4, 'instructor')], default=1),
        ),
    ]
