# Generated by Django 3.0.6 on 2020-05-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0086_userprofile_is_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('move_users', 'Can add or delete a user in the course'), ('delete_questions_from_course', 'Delete questions in the course question bank')]},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('create_question', 'Create a question'), ('update_question', 'Update a question')]},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'permissions': [('create_quiz', 'Create a quiz'), ('update_quiz', 'Update a quiz')]},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
    ]
