# Generated by Django 3.0.6 on 2020-05-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0087_auto_20200526_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_instructor',
        ),
    ]
