# Generated by Django 3.0.6 on 2020-06-09 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0087_auto_20200604_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('view_people', 'Can view the people in the course'), ('add_people', 'Can add a user to the course'), ('remove_people', 'Can remove people from the course'), ('delete_questions_from_course', 'Delete questions in the course question bank')]},
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
