# Generated by Django 3.0.6 on 2020-05-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0088_remove_userprofile_is_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
    ]
