# Generated by Django 3.0.6 on 2020-06-13 03:55

from django.db import migrations, models
import django.db.models.deletion
import polls.models.course


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0088_auto_20200609_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('view_people', 'Can view the people in the course'), ('add_people', 'Can add a user to the course'), ('remove_people', 'Can remove people from the course'), ('delete_questions_from_course', 'Delete questions in the course question bank'), ('access_code', 'Can access the secret code for enrolling students into the course')]},
        ),
        migrations.AddField(
            model_name='course',
            name='enroll_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Role'),
        ),
        migrations.AddField(
            model_name='course',
            name='secret_code',
            field=models.CharField(default=polls.models.course.random_code, max_length=10),
        ),
    ]
