# Generated by Django 3.0.6 on 2020-05-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0089_auto_20200527_0804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
