# Generated by Django 3.0.6 on 2020-06-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0091_userprofile_avatarurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatarurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
