# Generated by Django 3.0.8 on 2020-10-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0097_auto_20200930_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='pattern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='patternflag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
