# Generated by Django 3.0.8 on 2020-12-02 20:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0101_question_grade_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade_policy',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
