# Generated by Django 3.0.8 on 2020-12-02 20:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0102_auto_20201202_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade_policy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
