# Generated by Django 3.0.8 on 2020-12-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0103_auto_20201202_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='in_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
