# Generated by Django 3.0.8 on 2020-12-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0104_question_in_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='polls.Response'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='polls.Question'),
        ),
    ]
