# Generated by Django 3.0.8 on 2021-01-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0106_auto_20201216_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
