# Generated by Django 3.0.8 on 2021-01-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0107_quiz_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'permissions': [('view_others_attempts', "View other user's attempts.")]},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'permissions': [('view_gradebook', 'Can view the gradebook')]},
        ),
    ]
