# Generated by Django 3.0.8 on 2021-01-20 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0108_auto_20210120_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
