# Generated by Django 3.0.8 on 2021-03-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_linking_tables(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Users = apps.get_model("polls", "userprofile")
    AuthMethod = apps.get_model("polls", "AuthMethod")
    Preference = apps.get_model("polls", "Preference")
    Preference.objects.using(db_alias).create(title="12 Hour Time")
    Preference.objects.using(db_alias).create(title="Prefer Advanced Text")
    UserAuth = apps.get_model("polls", "UserAuthMethod")
    UserPreference = apps.get_model("polls", "UserPreference")
    for user in Users.objects.using(db_alias).all():
        for method in AuthMethod.objects.using(db_alias).all():
            UserAuth.objects.using(db_alias).create(user=user, method=method, value=True)
        for pref in Preference.objects.using(db_alias).all():
            UserPreference.objects.using(db_alias).create(user=user, preference=pref)

def reverse_linking_tables(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0109_question_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_methods',
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference', to='polls.Preference')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_authmethod', to='polls.AuthMethod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_authmethod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.UniqueConstraint(fields=('preference_id', 'user_id'), name='unique_preference'),
        ),
        migrations.AddConstraint(
            model_name='userauthmethod',
            constraint=models.UniqueConstraint(fields=('method_id', 'user_id'), name='unique_methods'),
        ),
        migrations.RunPython(add_linking_tables, reverse_linking_tables),
    ]
