# Generated by Django 3.0.8 on 2021-04-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0110_auto_20210301_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='patternfeedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
