# Generated by Django 3.0.8 on 2021-05-18 20:44

from django.db import migrations, models
import django.db.models.deletion
import polls.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0112_remove_attempt_quiz_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_file', models.FileField(storage=polls.models.image.MediaFileSystemStorage(), upload_to=polls.models.image.media_file_name)),
                ('md5sum', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_image', to='polls.Image')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_image', to='polls.Question')),
            ],
        ),
    ]
