# Generated by Django 3.0.8 on 2021-08-20 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0113_image_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 45, 16, 457441, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
