# Generated by Django 3.0.8 on 2022-01-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0116_answer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desc_as_title',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='question',
			old_name='title',
            new_name='descriptor',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
