# Generated by Django 3.0.8 on 2022-02-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0118_question_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correct',
            field=models.TextField(blank=True, null=True),
        ),
    ]
