# Generated by Django 3.0.8 on 2022-03-04 07:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import polls.models.quiz


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0119_response_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='begin_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_solution_date',
        ),
        migrations.AddField(
            model_name='quiz',
            name='review_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=polls.models.quiz.default_review_options),
        ),
    ]
