# Generated by Django 3.0.8 on 2022-04-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0121_attempt_last_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='last_save_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
