# Generated by Django 3.0.8 on 2023-01-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0124_auto_20220701_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='latexPreamble',
            field=models.TextField(blank=True, default=''),
        ),
    ]
