# Generated by Django 3.2 on 2023-02-17 04:28

from django.db import migrations, models
import polls.models.quiz
import polls.models.response


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0125_question_latexpreamble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='quiz_attempts',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade_policy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='tree',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='review_options',
            field=models.JSONField(default=polls.models.quiz.default_review_options),
        ),
        migrations.AlterField(
            model_name='response',
            name='rtype',
            field=models.JSONField(default=polls.models.response.default_string_dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
