# Generated by Django 3.2 on 2023-03-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0127_ltisecrets_quizlti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlti',
            name='userid',
        ),
        migrations.AddField(
            model_name='quizlti',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizlti',
            name='sourcedid',
            field=models.CharField(max_length=400),
        ),
    ]
