# Generated by Django 3.2 on 2023-03-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0128_auto_20230303_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonceTimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='LTISecrets',
            new_name='LTISecret',
        ),
    ]
